<?php

/**
 * @file
 * Primary module hooks for EIC Group membership module.
 */

use Drupal\Component\Serialization\Json;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Link;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Url;
use Drupal\eic_flags\FlagType;
use Drupal\eic_groups\EICGroupsHelper;
use Drupal\eic_groups\GroupsModerationHelper;
use Drupal\eic_group_membership\GroupMembershipHelper;
use Drupal\eic_overviews\GlobalOverviewPages;
use Drupal\eic_user\UserHelper;
use Drupal\grequest\Entity\Form\GroupMembershipApproveForm;
use Drupal\group\Access\GroupAccessResult;
use Drupal\group\Entity\Form\GroupContentForm;
use Drupal\group\Entity\GroupInterface;
use Drupal\group\GroupMembership;
use Drupal\oec_group_flex\GroupVisibilityRecordInterface;
use Drupal\message\Entity\Message;

/**
 * Implements hook_entity_operation_alter().
 */
function eic_group_membership_entity_operation_alter(
  array &$operations,
  EntityInterface $entity
) {
  if ($entity->getEntityTypeId() !== 'group_content') {
    return;
  }

  if ($entity->getContentPlugin()->getPluginId() !== 'group_membership') {
    return;
  }

  // Changes operation titles.
  foreach (array_keys($operations) as $key) {
    switch ($key) {
      case 'request_transfer_ownership':
      case 'accept_request_transfer_ownership':
      case 'deny_request_transfer_ownership':
      case 'cancel_request_transfer_ownership':
        break;

      case 'edit':
      case 'delete':
        // We replace the URL with our custom route, but keep the exact same
        // options and route parameters.
        $new_route_names = [
          'edit' => 'eic_group_membership.group_membership.edit_form',
          'delete' => 'eic_group_membership.group_membership.delete_form',
        ];
        /** @var \Drupal\Core\Url $old_url */
        $old_url = $operations[$key]['url'];
        $new_url = Url::fromRoute($new_route_names[$key]);
        $new_url->setOptions($old_url->getOptions());
        $new_url->setRouteParameters($old_url->getRouteParameters());
        $operations[$key]['url'] = $new_url;
        $operations[$key]['title'] = t('@operation member', ['@operation' => ucfirst($key)]);
        break;

      default:
        $operations[$key]['title'] = t('@operation member', ['@operation' => ucfirst($key)]);
        break;
    }
  }
}

/**
 * Implements hook_group_content_info_alter().
 */
function eic_group_membership_group_content_info_alter(array &$definitions) {
  if (isset($definitions['group_membership'])) {
    // Overrides the group_membership handlers.
    $definitions['group_membership']['handlers']['permission_provider'] = '\Drupal\eic_group_membership\Plugin\GroupMembershipPermissionProvider';
  }
}

/**
 * Implements hook_entity_field_access_alter().
 *
 * We need to alter the result of group_entity_field_access().
 * This is pretty much a verbatim copy of the above function, with just a change
 * in permissions checking.
 *
 * @see group_entity_field_access()
 */
function eic_group_membership_entity_field_access_alter(array &$grants, array $context) {
  // Can't retrieve an entity from an empty item list.
  if (!isset($context['items'])) {
    return;
  }

  // We only care about the group_roles field when on a form.
  if ($context['field_definition']->getName() != 'group_roles' || $context['operation'] !== 'edit') {
    return;
  }

  // We only care if it is attached to a group content entity.
  if ($context['items']->getEntity()->getEntityTypeId() != 'group_content') {
    return;
  }

  /** @var \Drupal\group\Entity\GroupContentInterface $group_content */
  $group_content = $context['items']->getEntity();

  // We only care if the group content entity is a group membership.
  if ($group_content->getContentPlugin()->getPluginId() != 'group_membership') {
    return;
  }

  // Now that we know we're dealing with a group_roles field on a group
  // membership form, we need to check whether the group membership belongs to a
  // group yet. If not, we can't check for access and should always hide it.
  if (!$group = $group_content->getGroup()) {
    return;
  }

  // Only group administrators should be able to change the membership roles.
  if ($group->hasPermission('administer members', $context['account'])
    || $group->hasPermission('edit memberships', $context['account'])) {
    $grants['group'] = AccessResult::allowed();
  }
}

/**
 * Implements hook_eic_page_contextual_actions().
 */
function eic_group_membership_eic_page_contextual_actions(array &$links, RouteMatchInterface $route, AccountInterface $account) {
  switch ($route->getRouteName()) {
    case 'view.eic_group_members.page_group_members':
      $group = $route->getParameter('group');
      $plugin_id = 'group_membership';
      $url = Url::fromRoute('entity.group_content.add_form', [
        'group' => $group->id(),
        'plugin_id' => $plugin_id,
      ]);
      $links[] = Link::fromTextAndUrl(t('Add member'), $url);
      break;
  }
}

/**
 * Implements hook_views_data_alter().
 */
function eic_group_membership_views_data_alter(&$data) {
  // Create a new views field for showing the group transfer ownership status
  // for each group member.
  $data['group_content']['transfer_ownership_status'] = [
    'title' => t('Member: show group transfer ownership status'),
    'group' => t('Group content'),
    'field' => [
      'id' => 'eic_group_membership_transfer_ownership_status',
      'title' => t('Group transfer ownership status'),
      'help' => t('Shows group transfer ownership status for the group member'),
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function eic_group_membership_form_alter(
  &$form,
  FormStateInterface $form_state,
  $form_id
) {
  if (GroupMembershipHelper::isGroupMembershipLeaveForm($form_id)) {
    /** @var \Drupal\group\Entity\GroupInterface $group */
    $group = $form_state->getFormObject()->getEntity()->getGroup();
    // Add our custom submit callback.
    $form['actions']['submit']['#submit'][] = 'eic_group_membership_leave_form_submit';
    // Change the cancel link URL to go back to the group entity itself.
    if (!empty($form['actions']['cancel']['#url'])) {
      $new_url = Url::fromRoute('entity.group.canonical', ['group' => $group->id()]);
      $form['actions']['cancel']['#url'] = $new_url;
    }
    // Change the title of the submit button.
    $form['actions']['submit']['#value'] = t('Leave');
    return;
  }

  // Handle group_membership form.
  _eic_group_membership_handle_group_membership_form($form, $form_state, $form_id);
  // Handle group_membership_request form.
  _eic_group_membership_handle_group_membership_request_form($form, $form_state, $form_id);
}

/**
 * Handle group_membership form.
 */
function _eic_group_membership_handle_group_membership_form(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityForm $form_object */
  $form_object = $form_state->getFormObject();
  if (!$form_object instanceof GroupContentForm) {
    return;
  }

  /** @var \Drupal\group\Entity\GroupContentInterface $entity */
  $entity = $form_object->getEntity();

  if ($entity->getContentPlugin()->getPluginId() !== 'group_membership') {
    return;
  }

  $group_type = $entity->getContentPlugin()->getGroupTypeId();
  $owner_role = $group_type . '-' . EICGroupsHelper::GROUP_TYPE_OWNER_ROLE;

  switch ($form_id) {
    case "group_content_{$group_type}-group_membership_add_form":
      // Remove the owner role.
      if (isset($form['group_roles']['widget']['#options'][$owner_role])) {
        unset($form['group_roles']['widget']['#options'][$owner_role]);
      }
      // Rename the options.
      foreach ($form['group_roles']['widget']['#options'] as $role_id => $role_name) {
        $form['group_roles']['widget']['#options'][$role_id] = t('Set as %role_name', [
          '%role_name' => $role_name,
        ]);
      }
      break;

    case "group_content_{$group_type}-group_membership_edit_form":
      // Remove the owner role.
      if (isset($form['group_roles']['widget']['#options'][$owner_role])) {
        unset($form['group_roles']['widget']['#options'][$owner_role]);
        array_unshift($form['actions']['submit']['#submit'], 'eic_group_membership_update_membership_role_form_submit');
      }
      // Rename the options.
      foreach ($form['group_roles']['widget']['#options'] as $role_id => $role_name) {
        $form['group_roles']['widget']['#options'][$role_id] = t('Set as %role_name', [
          '%role_name' => $role_name,
        ]);
      }
      // Replace the delete action link with our custom route.
      if (isset($form['actions']['delete']['#url'])) {
        /** @var \Drupal\Core\Url $old_url */
        $old_url = $form['actions']['delete']['#url'];
        $new_url = Url::fromRoute('eic_group_membership.group_membership.delete_form');
        $new_url->setRouteParameters($old_url->getRouteParameters());
        $new_url->setOptions($old_url->getOptions());
        $form['actions']['delete']['#url'] = $new_url;
      }
      break;

    case "group_content_{$group_type}-group_membership_group-join_form":
      $form['actions']['submit']['#value'] = t('Join');
      break;
  }
}

/**
 * Handle group_membership form.
 */
function _eic_group_membership_handle_group_membership_request_form(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\Core\Entity\EntityForm $form_object */
  $form_object = $form_state->getFormObject();
  if (!$form_object instanceof GroupMembershipApproveForm) {
    return;
  }

  /** @var \Drupal\group\Entity\GroupContentInterface $entity */
  $entity = $form_object->getEntity();

  if ($entity->getContentPlugin()->getPluginId() !== 'group_membership_request') {
    return;
  }

  $group_type = $entity->getContentPlugin()->getGroupTypeId();
  $owner_role = $group_type . '-' . EICGroupsHelper::GROUP_TYPE_OWNER_ROLE;

  switch ($form_id) {
    case "group_content_{$group_type}-group_membership_request_{$group_type}-approve-membership_form":
      // Remove the owner role.
      if (isset($form['roles']['#options'][$owner_role])) {
        unset($form['roles']['#options'][$owner_role]);
      }
      // Rename the options.
      foreach ($form['roles']['#options'] as $role_id => $role_name) {
        $form['roles']['#options'][$role_id] = t('Set as %role_name', [
          '%role_name' => $role_name,
        ]);
      }
      break;

  }
}

/**
 * Custom submit handler to keep the group owner role when editing membership.
 *
 * @param array $form
 *   An associative array containing the structure of the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 */
function eic_group_membership_update_membership_role_form_submit(
  array $form,
  FormStateInterface $form_state
) {
  /** @var \Drupal\group\Entity\GroupContentInterface $entity */
  $entity = $form_state->getFormObject()->getEntity();
  $current_group_owner = EICGroupsHelper::getGroupOwner($entity->getGroup());
  $specific_user = $entity->getEntity();
  $old_roles = $entity->get('group_roles')->getValue();
  $new_roles = $form_state->getValue('group_roles');
  $group_owner = EICGroupsHelper::getGroupOwner($entity->getGroup());

  $is_new_group_admin = array_filter($new_roles, function (array $role) use ($entity) {
    return $entity->getContentPlugin()->getGroupTypeId() . '-' . EICGroupsHelper::GROUP_TYPE_ADMINISTRATOR_ROLE
      === $role['target_id'];
  });

  // If user has no role and has been promoted to group_admin, send message.
  if (empty($old_roles) && count($is_new_group_admin) > 0) {
    /** @var \Drupal\eic_messages\Service\MessageBus $bus */
    $bus = \Drupal::service('eic_messages.message_bus');
    $message = Message::create([
      'template' => 'notify_group_admin_promoted',
      'field_group_ref' => ['target_id' => $entity->getGroup()->id()],
      'field_group_owner' => ['target_id' => $group_owner->id()],
      'field_event_executing_user' => ['target_id' => \Drupal::currentUser()->id()],
    ]);

    $message->setOwnerId($specific_user->id());

    $bus->dispatch($message);
  }

  // Keep the group owner role if we are editing the owner membership.
  if ($entity->getEntity()->id() === $current_group_owner->id()) {
    $owner_role = $entity->getContentPlugin()->getGroupTypeId() . '-' . EICGroupsHelper::GROUP_TYPE_OWNER_ROLE;
    $group_roles = $form_state->getValue('group_roles');
    $group_roles[] = [
      'target_id' => $owner_role,
    ];
    $form_state->setValue('group_roles', $group_roles);
  }
}

/**
 * Submit handler to set another redirect URL.
 *
 * @param array $form
 *   An associative array containing the structure of the form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The current state of the form.
 *
 * @throws \Drupal\Core\Entity\EntityMalformedException
 */
function eic_group_membership_leave_form_submit(
  array $form,
  FormStateInterface $form_state
) {
  /** @var \Drupal\group\Entity\GroupInterface $group */
  $group = $form_state->getFormObject()->getEntity()->getGroup();

  switch ($group->bundle()) {
    case 'group':
      $group_overview = GlobalOverviewPages::getGlobalOverviewPageLink(GlobalOverviewPages::GROUPS);
      $form_state->setRedirectUrl($group_overview->getUrl());
      break;

    case 'event':
      $group_overview = GlobalOverviewPages::getGlobalOverviewPageLink(GlobalOverviewPages::EVENTS);
      $form_state->setRedirectUrl($group_overview->getUrl());
      break;

    case 'organisation':
      $group_overview = GlobalOverviewPages::getGlobalOverviewPageLink(GlobalOverviewPages::ORGANISATIONS);
      $form_state->setRedirectUrl($group_overview->getUrl());
      break;
  }

  \Drupal::messenger()->addStatus(t('You successfully left the %group_type', [
    '%group_type' => $group->getGroupType()->label(),
  ]));
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function eic_group_membership_group_content_delete(EntityInterface $entity) {
  /** @var \Drupal\group\Entity\GroupContentInterface $entity */
  if ($entity->getContentPlugin()->getPluginId() !== 'group_membership') {
    return;
  }

  $user = $entity->getEntity();
  $flag_service = \Drupal::service('flag');
  $flag_entity = $entity->getGroup();
  $flag = $flag_service->getFlagById(FlagType::FOLLOW_GROUP);
  $flagging = $flag_service->getFlagging($flag, $flag_entity, $user);

  // User is following the group, so we force the unfollow when the user leaves
  // the group.
  if ($flagging) {
    $flag_service->unflag($flag, $flag_entity, $user);
  }

  $config = \Drupal::config('eic_group_membership.settings');
  // Setting to unfollow group content nodes when leaving the group is disabled
  // so we do nothing.
  if (!$config->get('unfollow_group_content_enqueue_items')) {
    return;
  }

  $group_visibility_storage = \Drupal::service('oec_group_flex.group_visibility.storage');
  $group_visibility = $group_visibility_storage->load($flag_entity->id());

  $exclude_group_visibilities = [
    'public',
    'restricted_community_members',
  ];

  if (UserHelper::isPowerUser($user)) {
    return;
  }

  // Creates queue items to unfollow group content nodes via drush command.
  if (!in_array($group_visibility->getType(), $exclude_group_visibilities)) {
    $queue = \Drupal::queue('eic_group_membership_unfollow_content');
    $queue->createItem([
      'gid' => $flag_entity->id(),
      'uid' => $user->id(),
    ]);
  }
}

/**
 * Implements hook_group_flex_visibility_save().
 */
function eic_group_membership_group_flex_visibility_save(
  GroupInterface $group,
  GroupVisibilityRecordInterface $old_group_visibility,
  GroupVisibilityRecordInterface $new_group_visibility
) {
  $config = \Drupal::config('eic_group_membership.settings');
  // Setting to unfollow group content nodes on visibility change is disabled,
  // so we do nothing.
  if (!$config->get('unfollow_group_content_enqueue_items')) {
    return;
  }

  if ($old_group_visibility->getType() !== $new_group_visibility->getType()) {
    switch ($new_group_visibility->getType()) {
      case 'private':
      case 'custom_restricted':
        $queue = \Drupal::queue('eic_group_membership_visibility_change_unfollow_content');
        $queue->createItem([
          'gid' => $group->id(),
        ]);
        break;

      default:
        break;

    }
  }
  else {
    switch ($new_group_visibility->getType()) {
      case 'custom_restricted':
        if (
          Json::encode($old_group_visibility->getOptions()) !==
          Json::encode($new_group_visibility->getOptions())
        ) {
          $queue = \Drupal::queue('eic_group_membership_visibility_change_unfollow_content');
          $queue->createItem([
            'gid' => $group->id(),
          ]);
        }
        break;

      default:
        break;

    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_access().
 */
function eic_group_membership_group_content_access(EntityInterface $entity, $operation, AccountInterface $account) {
  $access = GroupAccessResult::neutral();

  /** @var \Drupal\group\Entity\GroupContentInterface $entity */
  if ($entity->getContentPlugin()->getPluginId() !== 'group_membership') {
    return $access;
  }

  switch ($operation) {
    case 'edit':
      $group = $entity->getGroup();
      $is_power_user = UserHelper::isPowerUser($account, $group);
      $deny_moderation_states = [
        GroupsModerationHelper::GROUP_ARCHIVED_STATE,
        GroupsModerationHelper::GROUP_BLOCKED_STATE,
        GroupsModerationHelper::GROUP_PENDING_STATE,
        GroupsModerationHelper::GROUP_REFUSED_STATE,
      ];
      // Group is blocked or refused and therefore only power users can edit
      // group memberships.
      if (in_array($group->get('moderation_state')->value, $deny_moderation_states) && !$is_power_user) {
        $access = GroupAccessResult::forbidden()
          ->addCacheableDependency($account)
          ->addCacheableDependency($entity)
          ->addCacheableDependency($group);
      }
      break;
    case 'delete':
      $group = $entity->getGroup();
      $is_power_user = UserHelper::isPowerUser($account, $group);
      $deny_moderation_states = [
        GroupsModerationHelper::GROUP_ARCHIVED_STATE,
        GroupsModerationHelper::GROUP_BLOCKED_STATE,
        GroupsModerationHelper::GROUP_PENDING_STATE,
        GroupsModerationHelper::GROUP_REFUSED_STATE,
      ];

      // Group is blocked or refused and therefore only power users can delete
      // group memberships.
      if (in_array($group->get('moderation_state')->value, $deny_moderation_states) && !$is_power_user) {
        $access = GroupAccessResult::forbidden()
          ->addCacheableDependency($account)
          ->addCacheableDependency($entity)
          ->addCacheableDependency($group);
        break;
      }

      /** @var \Drupal\user\UserInterface $group_content_member */
      $group_content_member = $entity->getEntity();
      $group_owner = EICGroupsHelper::getGroupOwner($group);

      // Group owners cannot be deleted.
      if ($group_content_member->id() === $group_owner->id()) {
        $access = GroupAccessResult::forbidden()
          ->addCacheableDependency($account)
          ->addCacheableDependency($entity)
          ->addCacheableDependency($group);
        break;
      }

      /** @var \Drupal\eic_webservices\Utility\EicWsHelper $eic_ws_helper */
      $eic_ws_helper = \Drupal::service('eic_webservices.ws_helper');

      // Admins cannot be removed from SMED groups.
      if (
        $eic_ws_helper->isCreatedThroughSmed($group) &&
        !UserHelper::isPowerUser($account, $group) &&
        $group_admin_member = EICGroupsHelper::userIsGroupAdmin($group, $group_content_member)
      ) {
        $access = GroupAccessResult::forbidden()
          ->addCacheableDependency($entity)
          ->addCacheableDependency($group_admin_member)
          ->addCacheableDependency($group);
        break;
      }

      $current_member = $group->getMember($account);

      // We deny access if the user doesn't have permission to administer group
      // members or delete members.
      $has_delete_permission = ($group->hasPermission('administer members', $account) ||
        $group->hasPermission('delete memberships', $account));
      $access = GroupAccessResult::forbiddenIf(!$has_delete_permission)
        ->addCacheableDependency($account)
        ->addCacheableDependency($entity)
        ->addCacheableDependency($group);

      // Adds group membership as cacheable dependency.
      if ($current_member instanceof GroupMembership) {
        $access->addCacheableDependency($current_member);
      }
      break;

  }

  return $access;
}

/**
 * Implements hook_group_operations_alter().
 */
function eic_group_membership_group_operations_alter(array &$operations, GroupInterface $group) {
  if (isset($operations['group-join'])) {
    $operations['group-join']['title'] = t('Join');
  }
  if (isset($operations['group-request-membership'])) {
    $operations['group-request-membership']['title'] = t('Request membership');
  }
  if (isset($operations['group-leave'])) {
    $operations['group-leave']['title'] = t('Leave');
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_group_membership_group_content_insert(EntityInterface $entity) {
  switch ($entity->getContentPlugin()->getPluginId()) {
    case 'group_membership_request':
      // Get the ID of the user that requested a membership.
      $uid = $entity->getEntity()->id();
      $gid = $entity->getGroup()->id();

      // Clears the membership_request cache tag in order to update the
      // rendered output of the group header block.
      Cache::invalidateTags(["membership_request:$uid:$gid"]);
      break;

  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function eic_group_membership_group_content_update(EntityInterface $entity) {
  eic_group_membership_group_content_insert($entity);
}
