<?php

/**
 * @file
 * Primary module hooks for EIC Group membership module.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_operation_alter().
 */
function eic_group_membership_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->getEntityTypeId() !== 'group_content') {
    return;
  }

  if ($entity->getContentPlugin()->getPluginId() !== 'group_membership') {
    return;
  }

  // Changes operation titles.
  foreach (array_keys($operations) as $key) {
    switch ($key) {
      case 'request_transfer_ownership':
      case 'accept_request_transfer_ownership':
      case 'deny_request_transfer_ownership':
        break;

      default:
        $operations[$key]['title'] = t('@operation member', ['@operation' => ucfirst($key)]);
        break;

    }
  }
}

/**
 * Implements hook_views_data_alter().
 */
function eic_group_membership_views_data_alter(&$data) {
  // Create a new views field for showing the group transfer ownership status
  // for each group member.
  $data['group_content']['transfer_ownership_status'] = [
    'title' => t('Member: show group transfer ownership status'),
    'group' => t('Group content'),
    'field' => [
      'id' => 'eic_group_membership_transfer_ownership_status',
      'title' => t('Group transfer ownership status'),
      'help' => t('Shows group transfer ownership status for the group member'),
    ],
  ];
}
