<?php

/**
 * @file
 * Primary module hooks for EIC Group membership module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_entity_operation_alter().
 */
function eic_group_membership_entity_operation_alter(array &$operations, EntityInterface $entity) {
  if ($entity->getEntityTypeId() !== 'group_content') {
    return;
  }

  if ($entity->getContentPlugin()->getPluginId() !== 'group_membership') {
    return;
  }

  // Changes operation titles.
  foreach (array_keys($operations) as $key) {
    switch ($key) {
      case 'request_transfer_ownership':
      case 'accept_request_transfer_ownership':
      case 'deny_request_transfer_ownership':
        break;

      default:
        $operations[$key]['title'] = t('@operation member', ['@operation' => ucfirst($key)]);
        break;

    }
  }

  // @todo Remove code bellow

  // $url_options = [
  //   'query' => [
  //     'destination' => \Drupal::requestStack()->getCurrentRequest()->getRequestUri(),
  //   ],
  // ];

  // Adds transfer ownership operation.
  // $transfer_ownership_url = Url::fromRoute(
  //   'eic_group_membership.transfer_ownership.confirm_form',
  //   [
  //     'group' => $entity->getGroup()->id(),
  //     'group_content' => $entity->id(),
  //   ],
  //   $url_options
  // );
  // if ($transfer_ownership_url->access()) {
  //   $operations['transfer_ownership'] = [
  //     'title' => t('Transfer ownership'),
  //     'weight' => -50,
  //     'url' => $transfer_ownership_url,
  //   ];
  // }
}
