<?php

/**
 * @file
 * Provides an overview page entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function eic_overviews_theme() {
  return [
    'overview_page' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for overview page templates.
 *
 * Default template: overview-page.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the overview page information
 *     and any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_overview_page(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
