<?php

/**
 * @file
 * Primary module hooks for EIC Organisations module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\eic_organisations\Hooks\FormOperations;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function eic_organisations_form_group_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::classResolver(FormOperations::class)
    ->formGroupFormAlter($form, $form_state, $form_id);
}
