<?php

use Drupal\eic_events\Constants\Event;

/**
 * Implements hook_cron().
 */
function eic_events_cron() {
  // Value returned is timestamp.
  $last_request_time = \Drupal::state()
    ->get(Event::CRON_STATE_ID_LAST_REQUEST_TIME);

  $now = time();

  // Re-sync each 2 hours.
  if (0 >= ($last_request_time + 43200) - $now) {
    \Drupal::service('eic_events.update_solr_events')
      ->updateSolrEvents();

    \Drupal::state()->set(Event::CRON_STATE_ID_LAST_REQUEST_TIME, $now);
  }
}
