<?php

/**
 * @file
 * Primary module hooks for EIC Fragment type Fact &amp; Figure module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view_alter().
 */
function eic_fragment_fact_figure_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Adds the counter statistic of the Fact and Figure
  // into the build array.
  if ($entity->getEntityTypeId() == 'fragment' && $entity->bundle() == 'fact_figure') {

    /** @var \Drupal\eic_statistics\StatisticsStorageInterface $eic_statistics_storage */
    $eic_statistics_storage = \Drupal::service('eic_statistics.storage');

    switch ($entity->get('field_fact_figure_type')->getString()) {
      case 'members':
        $counter = $eic_statistics_storage->getEntityCounter('user');
        $cache_tag = $eic_statistics_storage->getEntityCounterCacheTag('user');
        break;

      case 'companies':
        $counter = $eic_statistics_storage->getEntityCounter('group', 'organisation');
        $cache_tag = $eic_statistics_storage->getEntityCounterCacheTag('group', 'organisation');
        break;

      case 'groups':
        $counter = $eic_statistics_storage->getEntityCounter('group', 'group');
        $cache_tag = $eic_statistics_storage->getEntityCounterCacheTag('group', 'group');
        break;

      case 'projects':
        $counter = $eic_statistics_storage->getEntityCounter('group', 'project');
        $cache_tag = $eic_statistics_storage->getEntityCounterCacheTag('group', 'peoject');
        break;

      case 'challenges':
        $counter = $eic_statistics_storage->getEntityCounter('node', 'challenge');
        $cache_tag = $eic_statistics_storage->getEntityCounterCacheTag('node', 'challenge');
        break;

      case 'events':
        $counter = $eic_statistics_storage->getEntityCounter('group', 'event');
        $cache_tag = $eic_statistics_storage->getEntityCounterCacheTag('group', 'event');
        break;

    }

    // Example showing the counter in a div tag.
    // @todo Remove this example once we have the theme ready.
    $build['example_counter'] = [
      '#type' => 'html_tag',
      '#tag' => 'div',
      '#value' => $counter,
      '#weight' => -50,
    ];

    // Adds the entity counter to the build array.
    $build['fact_figure_counter'] = $counter;
    // Adds statistic counter cache tag.
    $build['#cache']['tags'][] = $cache_tag;
  }
}

/**
 * Allowed values function for field_fact_figure_type.
 *
 * @return array
 *   Array of allowed values.
 */
function eic_field_fact_figure_type_allowed_values() {
  $string_translation = \Drupal::translation();
  return [
    'members' => $string_translation->translate('Members'),
    'companies' => $string_translation->translate('Companies'),
    'groups' => $string_translation->translate('Groups'),
    'projects' => $string_translation->translate('Projects'),
    'challenges' => $string_translation->translate('Challenges'),
    'events' => $string_translation->translate('Events'),
  ];
}
