version: '3'

services:
  apache:
    build:
      context: ./docker/apache
    ports:
      - 8087:80
    volumes:
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
      - .:/app
    links:
      - web
    container_name: ${APP_NAME}_apache

  web:
    image: fpfis/httpd-php-dev:7.3
    container_name: ${APP_NAME}_web
    working_dir: /var/www/html
    ports:
      - ${APP_PORT}:8080
    volumes:
      - .:/var/www/html
      - ./docker/bin/mhsendmail:/usr/local/bin/mhsendmail
      - ./docker/web/dev.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env

  nodejs:
    image: node:14-alpine
    container_name: ${APP_NAME}_nodejs
    volumes:
      - .:/app

  mysql:
    image: percona/percona-server:5.7
    container_name: ${APP_NAME}_mysql
    ports:
      - ${DATABASE_PORT}:3306
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: ${APP_NAME}_mailhog
    ports:
      - 1025:1025
      - 8025:8025

  solr:
    image: solr:7
    container_name: ${APP_NAME}_solr
    ports:
      - ${SOLR_PORT}:8983
    volumes:
      - solr_data:/var/solr
      - ./docker/solr/7.x:/opt/solr/server/solr/configsets/data_driven_schema_configs/conf
      - ./docker/solr/7.x:/opt/solr/server/solr/configsets/_default/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - eic

  redis:
    image: redis:alpine
    container_name: ${APP_NAME}_redis

volumes:
  mysql_data:
  solr_data:
