version: '3'

services:
  apache:
    build:
      context: ./docker/apache
    container_name: ${APP_NAME}_apache
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
      - .:${APP_ROOT}

  php:
    build:
      context: ./docker/php
    container_name: ${APP_NAME}_php
    working_dir: /app
    volumes:
      - .:${APP_ROOT}
      - ./docker/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      - ./docker/bin/mhsendmail:/usr/local/bin/mhsendmail
    env_file:
      - .env

  mysql:
    image: percona/percona-server:5.7
    container_name: ${APP_NAME}_mysql
    ports:
      - ${DATABASE_PORT}:3306
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - mysql_data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: ${APP_NAME}_mailhog
    ports:
      - 1025
      - ${MAILHOG_PORT}:8025

  solr:
    image: solr:7
    container_name: ${APP_NAME}_solr
    ports:
      - ${SOLR_PORT}:8983
    volumes:
      - solr_data:/var/solr
      - ./docker/solr/7.x:/opt/solr/server/solr/configsets/data_driven_schema_configs/conf
      - ./docker/solr/7.x:/opt/solr/server/solr/configsets/_default/conf
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - eic

  redis:
    image: redis:alpine
    container_name: ${APP_NAME}_redis

volumes:
  mysql_data:
  solr_data:
