<?php

/**
 * @file
 * Handles communications with EIC events
 *
 */

/**
 * Implements hook_queue_info().
 *
 * Queue names are initialized from annotations by \Drupal\Core\Plugin\DefaultPluginManager::findDefinitions().
 * It uses \Drupal\Component\Annotation\Plugin\Discovery\AnnotatedClassDiscovery to read the Doctrine annotations.
 * \Drupal\Core\Queue\QueueWorkerManager::alterInfo() will call this method to alter the queues description.
 *
 */
function eic_queue_queue_info_alter(&$queues) {
    $org_queue_name = \Drupal::config('eic_queue.settings')->get('org_queue_name');
    if ($org_queue_name != '')
    {
        $queues['EIC_ORG_QUEUE']['id'] = $org_queue_name;
        $queues[$org_queue_name] = $queues['EIC_ORG_QUEUE'];
        unset($queues['EIC_ORG_QUEUE']);
    }
}