<?php

/**
 * @file
 * Primary module hooks for EIC Search module.
 */

/**
 * Implements hook_theme().
 */
function eic_search_theme($existing, $type, $theme, $path) {
  return [
    'search_overview_block' => [
      'variables' => [
        'url' => '',
        'blockId' => 0,
        'isAnonymous' => TRUE,
        'translations' => [],
        'facets' => [],
        'sorts' => [],
        'results_per_page' => 0,
        'enable_search' => TRUE,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_block
 */
function eic_search_preprocess_block(&$variables) {
  $plugin_id = $variables['elements']['#plugin_id'];

  if ('eic_search_overview' !== $plugin_id) {
    return;
  }

  $variables['content']['#blockId'] = $plugin_id;
}
