<?php

/**
 * @file
 * Primary module hooks for EIC Search module.
 */

use Drupal\eic_groups\Constants\GroupVisibilityType;

/**
 * Implements hook_theme().
 */
function eic_search_theme($existing, $type, $theme, $path) {
  return [
    'search_overview_block' => [
      'variables' => [
        'url' => '',
        'blockId' => 0,
        'datasource' => '',
        'bundle' => '',
        'layout' => '',
        'isAnonymous' => TRUE,
        'translations' => [],
        'facets' => [],
        'sorts' => [],
        'page_options' => '',
        'currentGroup' => '',
        'currentGroupUrl' => '',
        'isGroupOwner' => FALSE,
        'enable_search' => TRUE,
        'source_class' => '',
        'search_string' => '',
        'enable_facet_interests' => FALSE,
        'enable_facet_my_groups' => FALSE,
        'allow_pagination' => FALSE,
        'load_more_number' => FALSE,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_html
 */
function eic_search_preprocess_html(&$variables) {
  /** @var \Drupal\eic_search\Collector\SourcesCollector $sources_provider */
  $sources_provider = \Drupal::service('eic_search.sources_collector');
  $sources = $sources_provider->getSources();

  /** @var \Drupal\eic_search\Search\Sources\SourceTypeInterface $source */
  foreach ($sources as $source) {
    foreach ($source->getAvailableSortOptions() as $sort_key => $options) {
      foreach ($options as $direction => $label) {
        $variables['#attached']['drupalSettings']['translations']['sources']['sort'][$sort_key . '__' . $direction] = $label;
      }
    }
    foreach ($source->getAvailableFacets() as $facet_option => $label) {
      $variables['#attached']['drupalSettings']['translations']['sources']['facet'][$facet_option] = $label;
    }
  }
}

/**
 * @implements hook_search_api_solr_documents_alter
 *
 * Solr needs to be aware of all group permissions so we can filter it in our
 *   querybuilder depending of the user context
 *
 * @throws \Drupal\Core\Entity\EntityMalformedException
 * @throws \Drupal\search_api\SearchApiException
 */
function eic_search_search_api_solr_documents_alter(array &$documents, \Drupal\search_api\IndexInterface $index, array $items) {
  /** @var \Drupal\eic_groups\EICGroupsHelper $group_helper */
  $group_helper = \Drupal::service('eic_groups.helper');
  /** @var \Drupal\eic_search\Service\SolrDocumentProcessor $solr_document_processor */
  $solr_document_processor = \Drupal::service('eic_search.solr_document_processor');

  /** @var \Solarium\QueryType\Update\Query\Document $document */
  foreach ($documents as $document) {
    $fields = $document->getFields();

    $solr_document_processor->processGlobalData($document, $fields);
    $solr_document_processor->processGroupData($document, $fields);
    $solr_document_processor->processDiscussionData($document, $fields);
    $solr_document_processor->processGroupUserData($document, $fields);
    $solr_document_processor->processGroupVisibilityData($document, $fields, $items, $group_helper);
  }
}
