<?php

/**
 * @file
 * Primary module hooks for EIC Datepicker module.
 */

use Drupal\eic_datepicker\Constants\Datepicker;

/**
 * Implements hook_preprocess_HOOK().
 */
function eic_datepicker_preprocess_input(&$variables) {
  // Get the active theme's name.
  $theme = \Drupal::theme()->getActiveTheme()->getName();

  // Attach only on date input template and on only type date (not time, datetime-local etc.)
  $is_date_type = $variables['theme_hook_original'] === 'input__date'
    && ($variables['element']['#attributes']['type'] === 'date');

  if (($theme === 'seven' && $is_date_type
    && in_array($variables['element']['#name'], Datepicker::FIELDS_OVERRIDE_DATEPICKER))) {
    // Attach custom library and add class identifier to element.
    $variables['#attached']['library'][] = 'eic_datepicker/datepicker';
    $variables["attributes"]["class"][] = 'js-datepicker-custom';

    // Set custom values for the library.
    $variables['attributes']['type'] = 'text';
    $variables['attributes']['placeholder'] = 'DD/MM/YYYY';
    $variables['attributes']['data-value'] = $variables['attributes']['value'];
  }
}
