check_sync_user: false
allow_user_register: true
user_registration_url: 'https://eic.eismea.eu/mydashboard/admissions/entry'
endpoint_url: ''
basic_auth_username: ''
basic_auth_password: ''
api_key: ''
