services:
  apache:
    volumes:
      - ./docker/apache/vhosts:/etc/apache2/sites-enabled
      - nfsmount:${APP_ROOT}
  php:
    volumes:
      - nfsmount:${APP_ROOT}
      - ./docker/php/dev.ini:/usr/local/etc/php/conf.d/dev.ini
      - ./docker/bin/mhsendmail:/usr/local/bin/mhsendmail

volumes:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":${PWD}/"
