<?php

use Drupal\Core\File\FileSystemInterface;


/**
 * Implements hook_install().
 */
function eic_projects_install($is_syncing) {
  $path = 'private://cordis-xml/export';
  \Drupal::service('file_system')->prepareDirectory($path, FileSystemInterface:: CREATE_DIRECTORY | FileSystemInterface::MODIFY_PERMISSIONS);
}

/**
 * Update field_project_total_cost and field_project_ecmax_contributio to match
 * config field storage settings
 */
function eic_projects_update_9000(&$sandbox) {
  $db = \Drupal::database();
  $numeric_fields = [
    [
      'table' => 'group__field_project_total_cost',
      'field' => 'field_project_total_cost_value',
    ],
    [
      'table' => 'group__field_project_ecmax_contributio',
      'field' => 'field_project_ecmax_contributio_value',
    ],
  ];
  foreach ($numeric_fields as $num_field) {
    $transaction = $db->startTransaction();
    $schema = $db->schema();
    try {
      // Define the schema object.

      $spec = [
        'type' => 'numeric',
        'precision' => 14,
        'scale' => 2,
        'not null' => TRUE,
      ];
      $schema->changeField($num_field['table'], $num_field['field'], $num_field['field'], $spec);

      // You can add other schema updates here if needed.

    } catch (\Exception $e) {
      // If there is an error, rollback the transaction.
      $transaction->rollback();
      // Log the error for debugging purposes.
      \Drupal::logger('eic_projects')->error($e->getMessage());
      // Rethrow the exception to stop further execution.
      throw $e;
    }

  }


}

/**
 * Rebuild the container to get the new service and class name for
 * eic_projects.project_migration
 */
function eic_projects_update_9001(&$sandbox) {
  // Rebuild the Drupal container during the update.
  \Drupal::service('kernel')->rebuildContainer();
}

/**
 * Update group project entities to add HRP links where possible.
 */
function eic_projects_update_9002(&$sandbox) {
  if (!isset($sandbox['total'])) {
    $gids = \Drupal::entityQuery('group')
      ->condition('type', 'project')
      ->accessCheck(FALSE)
      ->execute();
    $sandbox['total'] = count($gids);
    $sandbox['current'] = 0;

    if (empty($sandbox['total'])) {
      $sandbox['#finished'] = 1;
      return;
    }
  }

  $groups_per_batch = 25;
  $gids = \Drupal::entityQuery('group')
    ->condition('type', 'project')
    ->accessCheck(FALSE)
    ->range($sandbox['current'], $groups_per_batch)
    ->execute();
  if (empty($gids)) {
    $sandbox['#finished'] = 1;
    return;
  }

  foreach ($gids as $gid) {
    $url = \Drupal::service('eic_projects.ftp_search')->getPortalUrl($gid);
    if ($url) {
      $group = \Drupal::entityTypeManager()->getStorage('group')->load($gid);
      $link = [
        'uri' => $url,
        'title' => 'Horizon Results Platform',
      ];
      $group->set('field_project_horizon_results', $link);
      $group->save();
    }

    $sandbox['current']++;
  }

  \Drupal::messenger()
    ->addMessage($sandbox['current'] . ' groups processed.');

  if ($sandbox['current'] >= $sandbox['total']) {
    $sandbox['#finished'] = 1;
  }
  else {
    $sandbox['#finished'] = ($sandbox['current'] / $sandbox['total']);
  }
}
