<?php

/**
 * @file
 * Primary module hooks for EIC Messages module.
 */

use Drupal\Core\Entity\ContentEntityInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\eic_messages\Hooks\RequestMessageCreator;
use Drupal\eic_messages\Hooks\GroupContentMessageCreator;
use Drupal\eic_messages\Hooks\GroupMessageCreator;
use Drupal\flag\FlaggingInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_messages_group_insert(EntityInterface $entity) {
  /** @var GroupMessageCreator $class */
  $class = \Drupal::classResolver(GroupMessageCreator::class);
  $class->groupInsert($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function eic_messages_group_update(EntityInterface $entity) {
  /** @var GroupMessageCreator $class */
  $class = \Drupal::classResolver(GroupMessageCreator::class);
  $class->groupUpdate($entity);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_messages_group_content_insert(EntityInterface $entity) {
  /** @var GroupContentMessageCreator $class */
  $class = \Drupal::classResolver(GroupContentMessageCreator::class);
  $class->groupContentInsert($entity);
}

/**
 * Implements hook_request_insert().
 */
function eic_messages_request_insert(
  FlaggingInterface $flag,
  ContentEntityInterface $entity,
  string $type
) {
  /** @var RequestMessageCreator $class */
  $class = \Drupal::classResolver(RequestMessageCreator::class);
  $class->requestInsert($flag, $entity, $type);
}

/**
 * Implements hook_request_close().
 */
function eic_messages_request_close(
  FlaggingInterface $flag,
  ContentEntityInterface $entity,
  string $type
) {
  /** @var RequestMessageCreator $class */
  $class = \Drupal::classResolver(RequestMessageCreator::class);
  $class->requestClose($flag, $entity, $type);
}

/**
 * Implements hook_entity_type_alter().
 */
function eic_messages_entity_type_alter(array &$entity_types) {
  $entity_types['message_template']->setHandlerClass('form', [
    'add' => 'Drupal\eic_messages\Form\MessageTemplateForm',
    'edit' => 'Drupal\eic_messages\Form\MessageTemplateForm',
    'delete' => 'Drupal\message\Form\MessageTemplateDeleteConfirm',
  ]);
}

/**
 * Implements hook_views_data_alter().
 */
function eic_messages_views_data_alter(array &$data) {
  $data['message']['message_template_type'] = [
    'title' => t('Message template type'),
    'filter' => [
      'title' => t('Message template type'),
      'help' => t('Select the message template types to filter.'),
      'field' => 'template',
      'id' => 'message_template_type',
    ],
  ];
}
