<?php

/**
 * @file
 * Primary module hooks for EIC Messages module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\eic_messages\Hooks\EntityOperations;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_messages_group_insert(EntityInterface $entity) {
  \Drupal::classResolver(EntityOperations::class)
    ->groupInsert($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function eic_messages_group_update(EntityInterface $entity) {
  \Drupal::classResolver(EntityOperations::class)
    ->groupUpdate($entity);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_messages_group_content_insert(EntityInterface $entity) {
  /** @var EntityOperations $class */
  $class = \Drupal::classResolver(EntityOperations::class);
  $class->groupContentInsert($entity);
}
