<?php

/**
 * @file
 * Primary module hooks for EIC Messages module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\eic_messages\Hooks\GroupContentMessageCreator;
use Drupal\eic_messages\Hooks\GroupMessageCreator;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_messages_group_insert(EntityInterface $entity) {
  /** @var GroupMessageCreator $class */
  $class = \Drupal::classResolver(GroupMessageCreator::class);
  $class->groupInsert($entity);
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function eic_messages_group_update(EntityInterface $entity) {
  /** @var GroupMessageCreator $class */
  $class = \Drupal::classResolver(GroupMessageCreator::class);
  $class->groupUpdate($entity);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_messages_group_content_insert(EntityInterface $entity) {
  /** @var GroupContentMessageCreator $class */
  $class = \Drupal::classResolver(GroupContentMessageCreator::class);
  $class->groupContentInsert($entity);
}
