<?php

/**
 * @file
 * Primary module hooks for EIC User module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_user_presave().
 */
function eic_users_user_presave(EntityInterface $entity) {
  // Add full name as concatenated first and last name.
  $entity->set('field_full_name', implode(' ', [
    $entity->get('field_first_name')->value,
    $entity->get('field_last_name')->value,
  ]));
}
