<?php

/**
 * @file
 * The OE Theme Helper module.
 */

declare(strict_types = 1);

use Drupal\Component\Utility\Html;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\Entity\EntityViewDisplay;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\media\MediaInterface;
use Drupal\media\Plugin\media\Source\OEmbed;
use Drupal\media_avportal\Plugin\media\Source\MediaAvPortalVideoSource;
use Drupal\oe_media_iframe\Plugin\media\Source\Iframe;

/**
 * Implements hook_page_attachments().
 */
function eic_theme_helper_page_attachments(array &$page) {
  // Add ECL 2.0 required meta tags.
  $meta_default = [
    'ie_legacy_support' => [
      '#tag' => 'meta',
      '#attributes' => [
        'http-equiv' => 'X-UA-Compatible',
        'content' => 'IE=edge,chrome=1',
      ],
    ],
  ];
  foreach ($meta_default as $key => $value) {
    $page['#attached']['html_head'][] = [$value, $key];
  }

  // Load ECL component library assets for oe_theme and its subthemes.
  $active_theme = \Drupal::theme()->getActiveTheme();
  if ($active_theme->getName() === 'oe_theme' || array_key_exists('oe_theme', $active_theme->getBaseThemeExtensions())) {
    $component_library = theme_get_setting('component_library') ?? 'ec';
    $page['#attached']['library'][] = 'oe_theme/component_library_' . $component_library;
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function eic_theme_helper_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if (!isset($build['content_moderation_control'])) {
    return;
  }

  // Ensure that the content moderation control block will always
  // show at the top, above any other elements.
  $build['content_moderation_control']['#weight'] = -500;
}

/**
 * Implements hook_theme().
 */
function eic_theme_helper_theme($existing, $type, $theme, $path) {
  return [
    'eic_theme_helper_address_inline' => [
      'variables' => [
        'address' => NULL,
        'address_items' => [],
        'address_delimiter' => NULL,
      ],
    ],
    'eic_theme_helper_in_page_navigation' => [
      'render element' => 'element',
    ],
    'eic_theme_helper_featured_media' => [
      'variables' => [
        'params' => [],
      ],
    ],
    'eic_theme_helper_social_media_icons_list' => [
      'variables' => [
        'items' => [],
      ],
    ],
    'eic_theme_helper_social_media_links' => [
      'variables' => [
        'content' => [],
      ],
    ],
    'eic_theme_helper_site_navigation' => [
      'variables' => [
        'site_name' => '',
        'menu_items' => [],
      ],
    ],
    'eic_theme_helper_call_status' => [
      'variables' => [
        'label' => '',
        'name' => '',
      ],
    ],
    'eic_theme_helper_call_label_status' => [
      'variables' => [
        'label' => '',
        'name' => '',
      ],
    ],
    'eic_theme_helper_inpage_navigation_block' => [
      'variables' => [
        'title' => NULL,
      ],
    ],
  ];
}

/**
 * Prepares variables for in-page navigation.
 *
 * Default template: oe-theme-helper-in-page-navigation.html.twig.
 *
 * @param array $variables
 *   An array of variables.
 */
function template_preprocess_eic_theme_helper_in_page_navigation(array &$variables) {
  $variables['title'] = $variables['element']['#title'];
  $variables['entity'] = $variables['element']['#entity'];
  $variables['items'] = $variables['element']['#items'] ?? [];

  // Process in-page navigation items, assigning them a unique ID.
  foreach ($variables['items'] as $key => $item) {
    $variables['items'][$key]['id'] = strtolower(Html::cleanCssIdentifier($variables['items'][$key]['label']));
  }
}

/**
 * Prepares variables for featured media template.
 *
 * Default template: oe-theme-helper-featured-media.html.twig.
 *
 * @param array $variables
 *   An array of variables.
 */
function template_preprocess_oe_theme_helper_featured_media(array &$variables) {
  $field = $variables['field_name'];
  $params = ['description' => $variables['entity']->get($field)->caption];
  $media = $variables['entity']->get($field)->entity;

  if (!$media instanceof MediaInterface) {
    return $variables;
  }

  $cacheability = CacheableMetadata::createFromRenderArray($variables);
  // Run access checks on the media entity.
  $access = $media->access('view', NULL, TRUE);
  $cacheability->addCacheableDependency($access);
  $cacheability->applyTo($variables);
  if (!$access->isAllowed()) {
    return $variables;
  }
  // Retrieve the correct media translation.
  $media = \Drupal::service('entity.repository')->getTranslationFromContext($media, $variables['entity']->language()->getId());
  $cacheability->addCacheableDependency($media);

  // Get the media source.
  $source = $media->getSource();

  if ($source instanceof MediaAvPortalVideoSource || $source instanceof OEmbed || $source instanceof Iframe) {
    // Default video aspect ratio is set to 16:9.
    $params['ratio'] = '16-9';

    // Load information about the media and the display.
    $media_type = \Drupal::service('entity_type.manager')->getStorage('media_type')->load($media->bundle());
    $cacheability->addCacheableDependency($media_type);
    $source_field = $source->getSourceFieldDefinition($media_type);
    $display = EntityViewDisplay::collectRenderDisplay($media, 'oe_theme_main_content');
    $cacheability->addCacheableDependency($display);
    $display_options = $display->getComponent($source_field->getName());
    $oembed_type = $source->getMetadata($media, 'type');

    // If it is an OEmbed resource, render it and pass it as embeddable data
    // only if it is of type video or html.
    if ($source instanceof OEmbed && in_array($oembed_type, ['video', 'html'])) {
      $params['embedded_media'] = $media->{$source_field->getName()}->view($display_options);
      $variables['params'] = $params;
      $cacheability->applyTo($variables);

      return $variables;
    }

    // If its an AvPortal video or an iframe video, render it.
    $params['embedded_media'] = $media->{$source_field->getName()}->view($display_options);

    // When dealing with iframe videos, also respect its given aspect ratio.
    if ($media->bundle() === 'video_iframe') {
      $ratio = $media->get('oe_media_iframe_ratio')->value;
      $params['ratio'] = str_replace('_', '-', $ratio);
    }

    $variables['params'] = $params;
    $cacheability->applyTo($variables);

    return $variables;
  }

  // If it's an image media, render it and assign it to the image variable.
  /** @var \Drupal\image\Plugin\Field\FieldType\ImageItem $thumbnail */
  $thumbnail = $media->get('thumbnail')->first();
  /** @var \Drupal\Core\Entity\Plugin\DataType\EntityAdapter $file */
  $file = $thumbnail->get('entity')->getTarget();

  $image_url = '';
  $image_style = $variables['entity']->get($field)->getFieldDefinition()->getSetting('image_style');
  if ($image_style) {
    $style = \Drupal::service('entity_type.manager')->getStorage('image_style')->load($image_style);
    if ($style) {
      // Use image style url if set.
      $image_url = $style->buildUrl($file->get('uri')->getString());
      $cacheability->addCacheableDependency($image_style);
    }
  }
  if (empty($image_url)) {
    // Use original file url if image style is absent.
    $image_url = \Drupal::service('file_url_generator')->generateAbsoluteString($file->get('uri')->getString());
  }

  $params['alt'] = $thumbnail->get('alt')->getString();
  $params['image'] = $image_url;
  $variables['params'] = $params;
  $cacheability->applyTo($variables);

  return $variables;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function eic_theme_helper_theme_suggestions_eic_theme_helper_in_page_navigation(array $variables) {
  $suggestions = [];
  $element = $variables['element'];
  $hook = 'eic_theme_helper_in_page_navigation';

  $name = !empty($element['#group_name']) ? $element['#group_name'] : NULL;
  $entity_type = !empty($element['#entity_type']) ? $element['#entity_type'] : NULL;
  $bundle = !empty($element['#bundle']) ? $element['#bundle'] : NULL;

  if (!empty($name)) {
    $suggestions[] = $hook . '__' . $name;

    if (!empty($entity_type)) {
      $suggestions[] = $hook . '__' . $entity_type . '__' . $name;
    }
  }

  if (!empty($entity_type) && !empty($bundle)) {
    $suggestions[] = $hook . '__' . $entity_type . '__' . $bundle;

    if (!empty($name)) {
      $suggestions[] = $hook . '__' . $entity_type . '__' . $bundle . '__' . $name;
    }
  }

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function eic_theme_helper_theme_suggestions_eic_theme_helper_call_status(array $variables) {
  $suggestions = [];

  if (!empty($variables['name'])) {
    $suggestions[] = 'eic_theme_helper_call_status' . '__' . $variables['name'];
  }

  return $suggestions;
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function eic_theme_helper_theme_suggestions_eic_theme_helper_call_label_status(array $variables) {
  $suggestions = [];

  if (!empty($variables['name'])) {
    $suggestions[] = 'eic_theme_helper_call_label_status' . '__' . $variables['name'];
  }

  return $suggestions;
}

/**
 * Prepares variables for call status.
 *
 * Default template: oe-theme-helper-call-status.html.twig.
 *
 * @param array $variables
 *   An array of variables.
 */
function template_preprocess_eic_theme_helper_call_status(array &$variables) {
  if (!empty($variables['name'])) {
    $variables['attributes']['class'] = $variables['name'];
  }
}

/**
 * Implements hook_locale_translation_projects_alter().
 */
function eic_theme_helper_locale_translation_projects_alter(&$projects) {
  $projects['eic_theme_helper']['info']['interface translation server pattern'] = \Drupal::service('extension.path.resolver')
      ->getPath('module', 'eic_theme_helper') . '/translations/%project-%language.po';
}

/**
 * Implements hook_entity_bundle_info_alter().
 */
function eic_theme_helper_entity_bundle_info_alter(&$bundles) {
  if (!isset($bundles['media'])) {
    return;
  }

  $iframe_bundles = [
    'av_portal_video',
    'remote_video',
    'video_iframe',
  ];

  foreach ($bundles['media'] as $bundle_id => &$data) {
    $data['media_data_extractor'] = in_array($bundle_id, $iframe_bundles)
      ? 'iframe'
      : 'thumbnail';
  }
}

/**
 * Implements hook_form_FORM_ID_alter() for the entity view display form.
 */
function eic_theme_helper_form_entity_view_display_edit_form_alter(&$form, FormStateInterface $form_state) {
  if (!isset($form['#fieldgroups'])) {
    return;
  }
  foreach ($form['#fieldgroups'] as $name) {
    if ($form['fields'][$name]['human_name']['#markup'] === "") {
      $form['fields'][$name]['human_name']['#markup'] = t('- No label -');
    }
  }
}
