<?php

/**
 * @file
 * Main module file for EIC taxonomy module.
 */

use Drupal\taxonomy\Entity\Term;

const EIC_TAXONOMY_FIELDS_OF_SCIENCE_TERMS = [
  'bed7011f-e1bc-4e64-82f6-d5c7c005b945' =>
    [
      'name' => 'Social sciences',
      'vid' => 'fields_of_science',
      'machine_readable_name' => 'social-sciences',
    ],
  '885fe589-b98d-44a9-ac65-2438c91d527b' =>
    [
      'name' => 'Natural sciences',
      'vid' => 'fields_of_science',
      'machine_readable_name' => 'natural-sciences',
    ],
  '2976d993-3ddb-43bc-ae8f-295632d7e1e8' =>
    [
      'name' => 'Engineering and technology',
      'vid' => 'fields_of_science',
      'machine_readable_name' => 'engineering-and-technology',
    ],
  '5b633204-256a-4ea4-a516-7179ba3c0f1d' =>
    [
      'name' => 'Humanities',
      'vid' => 'fields_of_science',
      'machine_readable_name' => 'humanities',
    ],
  '850ce6cb-5044-4135-9180-06b4f43fb610' =>
    [
      'name' => 'Agricultural sciences',
      'vid' => 'fields_of_science',
      'machine_readable_name' => 'agricultural-sciences',
    ],
  'ff8b5564-fcde-4406-a91d-65485f11d0b3' =>
    [
      'name' => 'Medical and health sciences',
      'vid' => 'fields_of_science',
      'machine_readable_name' => 'medical-and-health-sciences',
    ],
  ];

/**
 * Implements hook_preprocess_HOOK() for taxonomy term templates.
 */
function eic_taxonomy_preprocess_taxonomy_term(&$variables) {
  // Get the term's UUID.
  $uuid = $variables['term']->uuid();

  // Check if the UUID has a corresponding class name in the constant.
  if (isset(EIC_TAXONOMY_FIELDS_OF_SCIENCE_TERMS[$uuid]['machine_readable_name'])) {
    // Add the class name to the term's attributes.
    $variables['machine_readable_name'] = EIC_TAXONOMY_FIELDS_OF_SCIENCE_TERMS[$uuid]['machine_readable_name'];
  }
}
