<?php

/**
 * @file
 * Main module file for EIC taxonomy module.
 */

use Drupal\eic_projects\Constants\Projects;

/**
 * Implements hook_preprocess_HOOK() for taxonomy term templates.
 */
function eic_taxonomy_preprocess_taxonomy_term(&$variables) {
  // Get the term's UUID.
  $uuid = $variables['term']->uuid();

  // Check if the UUID has a corresponding class name in the constant.
  if (isset(Projects::EIC_TAXONOMY_FIELDS_OF_SCIENCE_TERMS[$uuid]['machine_readable_name'])) {
    // Add the class name to the term's attributes.
    $variables['machine_readable_name'] = Projects::EIC_TAXONOMY_FIELDS_OF_SCIENCE_TERMS[$uuid]['machine_readable_name'];
  }
}
