<?php

use Drupal\eic_share_content\Hooks\SolrDocumentDecorator;

/**
 * Implements hook_theme().
 */
function eic_share_content_theme() {
  return [
    'eic_share_content_link' => [
      'variables' => [
        'endpoint' => NULL,
        'get_groups_url' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_search_api_solr_documents_alter.
 *
 * @param array $documents
 * @param \Drupal\search_api\IndexInterface $index
 * @param array $items
 *
 * @throws \Drupal\Component\Plugin\Exception\InvalidPluginDefinitionException
 * @throws \Drupal\Component\Plugin\Exception\PluginNotFoundException
 */
function eic_share_content_search_api_solr_documents_alter(
  array &$documents,
  \Drupal\search_api\IndexInterface $index,
  array $items
) {
  /** @var SolrDocumentDecorator $decorator */
  $decorator = \Drupal::classResolver(SolrDocumentDecorator::class);
  foreach ($documents as &$document) {
    $fields = $document->getFields();
    if (
      !isset($fields['ss_search_api_datasource'])
      || $fields['ss_search_api_datasource'] !== 'entity:node'
    ) {
      continue;
    }

    $document = $decorator->decorate($document);
  }
}
