<?php

use Drupal\eic_subscription_digest\Constants\DigestTypes;
use Drupal\eic_subscription_digest\Hooks\DigestNotificationCron;


/**
 * Implements hook_cron().
 */
function eic_subscription_digest_cron() {
  \Drupal::classResolver(DigestNotificationCron::class)->sendNotifications();
}

/**
 * @return array
 */
function eic_subscription_digest_get_digest_frequencies(): array {
  $types = DigestTypes::getAll();

  return array_combine($types, array_map('ucfirst', $types));
}
