<?php

/**
 * @file
 * Primary module hooks for EIC Group Statistics module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\eic_group_statistics\GroupStatisticsStorageInterface;
use Drupal\eic_group_statistics\Hooks\EntityOperations;
use Drupal\group\Entity\GroupContent;

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function eic_group_statistics_group_delete(EntityInterface $entity) {
  \Drupal::service('eic_group_statistics.storage')->deleteGroupStatistics($entity);
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_group_statistics_group_content_insert(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'group-group_membership':
    case 'group-group_node-document':
    case 'group-group_node-wiki_page':
    case 'group-group_node-gallery':
      \Drupal::classResolver(EntityOperations::class)
        ->groupContentInsert($entity);
      break;

  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function eic_group_statistics_group_content_delete(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'group-group_membership':
      \Drupal::classResolver(EntityOperations::class)
        ->groupContentDelete($entity);
      break;

  }
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function eic_group_statistics_node_delete(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'document':
    case 'wiki_page':
    case 'gallery':
      // We need to make sure the node belongs to a group content, otherwise we
      // don't need to update any group statistics.
      $group_contents = GroupContent::loadByEntity($entity);
      if (!$group_contents) {
        return;
      }

      $group_content = reset($group_contents);

      \Drupal::classResolver(EntityOperations::class)
        ->groupContentNodeDelete($entity, $group_content);
      break;

  }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_group_statistics_comment_insert(EntityInterface $entity) {
  $commented_entity = $entity->getCommentedEntity();

  // We need to make sure the comment belongs to a group content, otherwise we
  // don't need to update any group statistics.
  $group_contents = GroupContent::loadByEntity($commented_entity);
  if (!$group_contents) {
    return;
  }

  $group_content = reset($group_contents);

  // Increments group comments statistic counter.
  \Drupal::service('eic_group_statistics.storage')->increment($group_content->getGroup(), GroupStatisticsStorageInterface::STAT_TYPE_COMMENTS);

  // Re-index group statistics.
  \Drupal::service('eic_group_statistics.search_api.reindex')->reindexItem($group_content->getGroup());
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
function eic_group_statistics_comment_delete(EntityInterface $entity) {
  $commented_entity = $entity->getCommentedEntity();

  // We need to make sure the comment belongs to a group content, otherwise we
  // don't need to update any group statistics.
  $group_contents = GroupContent::loadByEntity($commented_entity);
  if (!$group_contents) {
    return;
  }

  $group_content = reset($group_contents);

  // Decrements group comments statistic counter.
  \Drupal::service('eic_group_statistics.storage')->decrement($group_content->getGroup(), GroupStatisticsStorageInterface::STAT_TYPE_COMMENTS);

  // Re-index group statistics.
  \Drupal::service('eic_group_statistics.search_api.reindex')->reindexItem($group_content->getGroup());
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function eic_group_statistics_node_update(EntityInterface $entity) {
  switch ($entity->bundle()) {
    case 'document':
    case 'wiki_page':
    case 'gallery':
      // We need to make sure the node belongs to a group content, otherwise we
      // don't need to update any group statistics.
      $group_contents = GroupContent::loadByEntity($entity);
      if (!$group_contents) {
        return;
      }

      $group_content = reset($group_contents);

      \Drupal::classResolver(EntityOperations::class)
        ->groupContentNodeUpdate($entity, $group_content);
      break;

  }
}
