<?php

/**
 * @file
 * Primary module hooks for EIC Message Notifications module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\eic_message_subscriptions\Hooks\EntityOperations;
use Drupal\eic_message_subscriptions\Hooks\FormOperations;
use Drupal\node\Entity\NodeType;

/**
 * Implements hook_entity_insert().
 */
function eic_message_subscriptions_entity_insert(EntityInterface $entity) {
  switch ($entity->getEntityTypeId()) {
    case 'comment':
      \Drupal::classResolver(EntityOperations::class)
        ->entityInsert($entity);
      break;

    case 'group_content':
      \Drupal::classResolver(EntityOperations::class)
        ->entityInsert($entity);
      break;

  }
}

/**
 * Implements hook_entity_extra_field_info().
 */
function eic_message_subscriptions_entity_extra_field_info() {
  $extra = [];

  // We add the extra field for all content types. The display will be handled
  // in the hook_form_BASE_FORM_ID_alter() function.
  foreach (NodeType::loadMultiple() as $bundle) {
    $extra['node'][$bundle->id()]['form']['field_send_notification'] = [
      'label' => t('Send notification'),
      'description' => '',
      'visible' => TRUE,
    ];
  }

  return $extra;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function eic_message_subscriptions_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  \Drupal::classResolver(FormOperations::class)
    ->entityFormAlter($form, $form_state, $form_id);
}
