<?php

/**
 * @file
 * Primary module hooks for EIC Content Book module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\BubbleableMetadata;
use Drupal\eic_content_book\Hooks\BookTokens;
use Drupal\eic_content_book\Hooks\EntityOperations;
use Drupal\eic_content_book\Hooks\Preprocess;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function eic_content_book_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  \Drupal::classResolver(EntityOperations::class)
    ->nodeView($build, $entity, $display, $view_mode);
}

/**
 * Implements hook_preprocess_links__node().
 */
function eic_content_book_preprocess_links__node(&$variables) {
  \Drupal::classResolver(Preprocess::class)
    ->preprocessLinksNode($variables);
}

/**
 * Implements hook_token_info().
 */
function eic_content_book_token_info() {
  /** @var \Drupal\eic_content_book\Hooks\BookTokens $class */
  $class = \Drupal::classResolver(BookTokens::class);
  return $class->tokenInfo();
}

/**
 * Implements hook_tokens().
 */
function eic_content_book_tokens($type, $tokens, array $data, array $options, BubbleableMetadata $bubbleable_metadata) {
  /** @var \Drupal\eic_content_book\Hooks\BookTokens $class */
  $class = \Drupal::classResolver(BookTokens::class);
  return $class->tokens($type, $tokens, $data, $options, $bubbleable_metadata);
}

/**
 * Implements hook_form_alter().
 */
function eic_content_book_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (strpos($form_id, '_book_outline_form') !== FALSE) {
    // We don't allow users to select the book.
    $form['book']['bid']['#access'] = FALSE;
  }
}
