<?php

/**
 * @file
 * Primary module hooks for EIC Content Book module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\eic_content_book\Hooks\EntityOperations;
use Drupal\eic_content_book\Hooks\Preprocess;

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function eic_content_book_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  \Drupal::classResolver(EntityOperations::class)
    ->nodeView($build, $entity, $display, $view_mode);
}

/**
 * Implements hook_preprocess_links__node().
 */
function eic_content_book_preprocess_links__node(&$variables) {
  \Drupal::classResolver(Preprocess::class)
    ->preprocessLinksNode($variables);
}
