<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\eic_dashboards\Hooks\EntityOperations;
use Drupal\path_alias\Entity\PathAlias;
use Drupal\Core\Template\Attribute;

/**
 * Implements hook_theme().
 */
function eic_dashboards_theme($existing, $type, $theme, $path) {
  return [
    'chart_column' => [
      'variables' => [
        'title' => '',
        'categories' => '',
        'series' => '',
        'vertical' => false,
      ],
    ],
    'dashboards_homepage' => [
      'variables' => [
        'title' => '',
        'dashboards' => NULL,
        'content' => NULL,
        'listings' => NULL,
      ],
    ],
    'columns' => [
      'variables' => [
        'items' => '',
        'size' => '',
        'attributes' => [],
      ],
    ],
    'cta_card' => [
      'variables' => [
        'title' => '',
        'link' => '',
        'icon' => '',
        'variant' => '',
        'path' => '',
      ],
    ],
    'number_and_link' => [
      'variables' => [
        'title' => '',
        'number' => '',
        'link' => '',
      ],
    ],
    'chart_pie' => [
      'variables' => [
        'title' => '',
        'data' => '',
        'size' => '',
      ],
    ],
    'chart_with_menu' => [
      'variables' => [
        'chart' => '',
        'menu' => '',
      ],
    ],
    'jump_menu' => [
      'variables' => [
        'wrapper_attributes' => [],
        'placeholder' => '',
        'title' => '',
        'title_attributes' => [],
        'items' => [],
        'attributes' => [],
      ],
    ],
    'title_link_list' => [
      'variables' => [
        'title' => '',
        'link' => '',
        'list' => '',
      ],
    ],
    'tabs' => [
      'variables' => [
        'title' => '',
        'items' => [],
      ],
    ],
    'report_list' => [
      'variables' => [
        'title' => '',
        'link' => '',
        'items' => '',
      ],
    ],
    'dashboard_section' => [
      'variables' => [
        'title' => '',
        'link' => '',
        'content' => '',
        'icon' => '',
        'path' => '',
        'has_border' => true,
      ],
    ],
  ];
}

/**
 * Implements hook_page_attachments().
 */
function eic_dashboards_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'eic_dashboards/general';
  $attachments['#attached']['library'][] = 'eic_dashboards/scripts';
}

/**
 * Implements hook_page().
 */
function eic_dashboards_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'eic_dashboards/dashboards_menu';

  $route_match = \Drupal::routeMatch();
  $route_name = $route_match->getRouteName();

  // Only apply on specific Views pages
  if ($route_name === 'view.dashboard_content_list.page'
    || $route_name === 'view.dashboard_organisations_list.page'
    || $route_name === 'view.dashboard_members_list.page'
    || $route_name === 'view.dashboard_projects_list.page'
    || $route_name === 'view.dashboard_organisations_list.page'
    || $route_name === 'eic_dashboards.members'
    || $route_name === 'eic_dashboards.group.groups'
    || $route_name === 'eic_dashboards.group.events'
    || $route_name === 'eic_dashboards.group.organisations'
    || $route_name === 'eic_dashboards.group.projects'
    || $route_name === 'eic_dashboards.content.documents'
    || $route_name === 'eic_dashboards.content.stories'
    || $route_name === 'eic_dashboards.content.discussions'
    || $route_name === 'eic_dashboards.listings.activity_report') {

    // Inject a custom render array into the content region
    $variables['page']['content']['custom_dashboard_banner'] = [
      '#type' => 'markup',
      '#markup' => '
        <div class="ecl-overview-header">
          <div class="ecl-container">
            <div class="ecl-overview-header__content">
              <div class="ecl-overview-header__main">
                <h1 class="ecl-overview-header__title">' . htmlspecialchars($variables['page']['#title']) . '</h1>
              </div>
            </div>
          </div>
        </div>
      ',
      '#allowed_tags' => ['div', 'h1'], // Optional: whitelist HTML tags
      '#weight' => -100, // Put it at the top
    ];
  }
}

/**
 * Implements hook_views_data().
 */
function eic_dashboards_views_data() {
  $data = [];

  $data['views']['user_profile_completion_status'] = [
    'title' => t('User profile completion status'),
    'filter' => [
      'title' => t('User profile completion status'),
      'group' => t('User'),
      'help' => t('Filters user by profile completion'),
      'field' => 'id',
      'id' => 'user_profile_completion_status',
    ],
  ];

  return $data;
}

/**
 * Implements hook_views_data_alter().
 */
function eic_dashboards_views_data_alter(array &$data) {
  $data['users']['user_organisation_group_memberships'] = [
    'title' => t('User organisation group memberships'),
    'group' => t('User'),
    'field' => [
      'title' => t('User organisation group memberships'),
      'help' => t('Retrieves the organisations a user belongs to.'),
      'id' => 'user_organisation_group_memberships',
    ],
  ];

  $data['users']['user_profile_completion_status'] = [
    'title' => t('User Profile completion status'),
    'group' => t('User'),
    'field' => [
      'title' => t('User Profile completion status'),
      'help' => t('Reports if a user profile is completed or not.'),
      'id' => 'user_profile_completion_status',
    ],
  ];

  $data['node']['content_flag_follows'] = [
    'title' => t('Number of follows'),
    'group' => t('Content'),
    'field' => [
      'title' => t('Number of follows'),
      'help' => t('Show number of content flag follows.'),
      'id' => 'content_flag_follows',
    ],
  ];

  $data['node']['content_flag_likes'] = [
    'title' => t('Number of likes'),
    'group' => t('Content'),
    'field' => [
      'title' => t('Number of likes'),
      'help' => t('Show number of content flag likes.'),
      'id' => 'content_flag_likes',
    ],
  ];
}

/**
 * Create aliases for given group paths.
 */
function _eic_communities_create_alias($group_id, $group_name, $group_paths) {
  foreach ($group_paths as $group_path) {
    PathAlias::create([
      'path' => '/group/' . $group_id . '/' . $group_path,
      'alias' => '/communities/' . $group_name . '/' . $group_path,
    ])->save();
  }
}

/**
 * Prepares variables for EIC Dashboard jump menu template.
 *
 * Default template: jump-menu.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - items: An array of items to be displayed in the select.
 *   - title: A title to be prepended to the list.
 */
function template_preprocess_jump_menu(array &$variables) {
  $variables['wrapper_attributes'] = new Attribute($variables['wrapper_attributes']);
  $variables['title_attributes'] = new Attribute($variables['title_attributes']);

  foreach ($variables['items'] as &$item) {
    $attributes = [];
    if (isset($item['#attributes'])) {
      $attributes = $item['#attributes'];
    }
    // Set the item's value and attributes for the template.
    $item = [
      'label' => $item['#label'],
      'value' => $item['#value'],
      'attributes' => new Attribute($attributes),
    ];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function eic_dashboards_form_views_exposed_form_alter(&$form, FormStateInterface $form_state, $form_id) {
 if ($form['#id'] === 'views-exposed-form-dashboard-members-list-page') {
   $form['status_1']['#options'][1] = t('Enabled');
   $form['status_1']['#options'][0] = t('Disabled');
 }
}

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_dashboards_group_insert(EntityInterface $entity) {
  \Drupal::classResolver(EntityOperations::class)->createGroupDashboardPageMenuLink($entity);
}

/**
 * Implements hook_preprocess_views_view().
 */
function eic_dashboards_preprocess_views_view(array &$variables) {
  $view = $variables['view'];

  // List of view IDs you want to target.
  $target_view_ids = [
    'dashboard_content_list',
    'dashboard_organisations_list',
    'dashboard_members_list',
    'dashboard_projects_list'
  ];

  if (in_array($view->id(), $target_view_ids, true)) {
    $variables['header_classes'][] = 'ecl-container ecl-u-mt-m';
  }
}
