<?php

use Drupal\path_alias\Entity\PathAlias;

/**
 * Implements hook_theme().
 */
function eic_dashboards_theme($existing, $type, $theme, $path) {
  return [
    'dashboards_homepage' => [
      'variables' => [
        'title' => '',
        'dashboards' => NULL,
        'listings' => NULL,
      ],
    ],
    'columns' => [
      'variables' => [
        'items' => '',
        'size' => '',
        'attributes' => [],
      ],
    ],
    'cta_card' => [
      'variables' => [
        'title' => '',
        'link' => '',
        'icon' => '',
        'variant' => '',
        'path' => '',
      ],
    ],
    'number_and_link' => [
      'variables' => [
        'title' => '',
        'number' => '',
        'link' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_page().
 */
function eic_dashboards_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'eic_dashboards/dashboards_menu';
}

/**
 * Implements hook_views_data_alter().
 */
function eic_dashboards_views_data_alter(array &$data) {
  $data['users']['user_organisation_group_memberships'] = [
    'title' => t('User organisation group memberships'),
    'group' => t('Users'),
    'field' => [
      'title' => t('User organisation group memberships'),
      'help' => t('Retrieves the organisations a user belongs to.'),
      'id' => 'user_organisation_group_memberships',
    ]
  ];
}

/**
 * Create aliases for given group paths.
 */
function _eic_communities_create_alias($group_id, $group_name, $group_paths) {
  foreach ($group_paths as $group_path) {
    PathAlias::create([
      'path' => '/group/' . $group_id . '/' . $group_path,
      'alias' => '/communities/' . $group_name . '/' . $group_path,
    ])->save();
  }
}
