<?php

use Drupal\Core\Extension\ExtensionPathResolver;

/**
 * Implements hook_theme().
 */
function eic_dashboards_theme($existing, $type, $theme, $path) {
  return [
    'dashboards_homepage' => [
      'variables' => [
        'title' => '',
        'dashboards' => NULL,
        'listings' => NULL,
      ],
    ],
    'cta_card' => [
      'variables' => [
        'title' => '',
        'link' => '',
        'icon' => '',
        'variant' => '',
        'path' => '',
      ],
    ]
  ];
}

/**
 * Implements hook_page().
 */
function eic_dashboards_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'eic_dashboards/dashboards_menu';
}
