<?php

/**
 * @file
 * Main module file for EIC Comments module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function eic_comments_form_comment_node_comment_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form_comment_body = &$form['comment_body']['widget'];

  $form['comment_body']['#attributes']['class'][] = 'ecl-comment-form__textarea-wrapper';
  $form_comment_body[0]['#placeholder'] = 'Jot something down!';
  $form_comment_body[0]['#title_display'] = 'invisible';

  array_push($form_comment_body[0]['#attributes']['class'],
  'ecl-text-area',
  'ecl-comment-form__textarea',
  'ecl-comment-form-reply'
  );
  $form_comment_body['#after_build'][] = 'eic_comments_configure_comment_form';

  $form['actions']['preview']['#access'] = FALSE;
  $form["actions"]["submit"]["#value"] = 'Publish';
}

/**
 * Callback function to hide text format information.
 */
function eic_comments_configure_comment_form($form) {
  $form[0]['format']['#access'] = FALSE;
  return $form;
}
