<?php

/**
 * @file
 * Primary module hooks for EIC Content Discussion module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\eic_content_discussion\Hooks\EntityOperations;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_content_discussion_node_insert(\Drupal\node\NodeInterface $entity) {
  if ('discussion' === $entity->bundle()) {
    \Drupal::classResolver(EntityOperations::class)
      ->discussionInsert($entity);
  }
}
