<?php

/**
 * @file
 * Primary module hooks for EIC Content Discussion module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\eic_content_discussion\Hooks\EntityOperations;
use Drupal\node\NodeInterface;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function eic_content_discussion_node_insert(NodeInterface $entity) {
  if ('discussion' === $entity->bundle()) {
    \Drupal::classResolver(EntityOperations::class)
      ->discussionInsert($entity);
  }
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function eic_content_discussion_node_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  if ('discussion' === $entity->bundle()) {
    \Drupal::classResolver(EntityOperations::class)
      ->nodeView($build, $entity, $display, $view_mode);
  }
}
